version: '3.8'

services:
  redis: 
    image: redis/redis-stack:latest
    ports: 
      - "${REDIS_PORT}:6379"
      - "8001:8001"      
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASS}

  mongodb: 
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DBNAME}
